### ISSUE TITLE
Pass parameters through the geoprocessing script 

### ISSUE THREAD

**Issue by danyocum** [seasketch/geoprocessing#13]
To allow an individual test to be run (and probably other stuff, too). It eats the parameters now and they don't get passed along to jest.

**Comment by underbluewaters** [comment]
Appears this works by just prepending arguments with `--`. Need to update documentation

**Comment by danyocum** [comment]
to pass arguments to jest from npm, separate npm command from jest with -- 
for example:

npm test -- -t=areaTest (will run the test matching the target name 'areaTest')
npm test -- --group=smoke (to run the smoke tests in a project)

the test needs to have the following in the beginning of the file 
/**
* @group smoke
*/

**Comment by danyocum** [comment]
Updated the README.md
