### ISSUE TITLE
ReportContext isn't updated by SeaSketchReportingVisibleLayersChangeEvent?

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#131]
SeaSketch Next is now sending SeaSketchReportingVisibleLayersChangeEvent to report clients but layer toggle buttons don't appear to update. I'm not certain whether this is a bug in the report client app, or a problem with the message I'm sending from SSN.

**Comment by avmey** [comment]
@underbluewaters Is this still occurring? I haven't seen this behavior.

**Comment by twelch** [comment]
This was fixed.  Seasketch layer menu and reports stay in sync now, even if multiple open
