### ISSUE TITLE
Add multipolygon support to geoblaze

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#160]
Geoblaze currently only supports overlay of a single polygon.  But SeaSketch Next intends to support multipolygons, created through for example user drawing a polygon and being clipped against one or more datasources.

Goal - geoprocessing functions are able to take a multipolygon sketch and calculate raster stats with Geoblaze.

Requirements:
- [x] Allow geojson multipolygon as input to geoblaze functions
- [x] Should not double count in raster stats where two or more of the polygons in the multipolygon are overlapping. 

Geoblaze Tasks:
- [x] Confirm/implement multipolygon support
- [x] Add unit test(s)

Follow-on gp tasks:
- [x] Add multipolygon support to raster toolbox functions
- [ ] Add unit test(s)

**Comment by DanielJDufour** [comment]
This a great catch.  That's a mistake in the way geoblaze is using [dufour-peyton-intersection](https://github.com/geotiff/dufour-peyton-intersection).

**Comment by twelch** [comment]
Great.  I went ahead and added the gp lib integration as follow-on tasks.  As I've hinted, the work to be done in the gp library could be a natural place for me to also contribute and we can collaborate on both sides in discussion and code review, making sure the upstream geoblaze changes meet the needs.
