### ISSUE TITLE
Solve pain point in using template-ocean-eez

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#168]
Particularly switching from using EEZ to using a local boundary (nearshore/offshore)

cc @avmey 
[NOTES]

Possible solutions:
- Create an ocean-nearshore-template
- Make ocean-eez-template less eez specific and auto-generate nearshore and offshore boundaries
- Document how to add a new boundary, with code snippets for preprocessor and boundaryAreaOverlap function

**Comment by avmey** [comment]
I think documenting would solve the pain point fine. Maybe best location would be in geoprocessing/packages/template-ocean-eez/README.md. I can put my notes in there after you've merged in the other documentation edits you've been working on.

**Comment by avmey** [comment]
Current thought is to add to [Extending](https://github.com/seasketch/geoprocessing/wiki/Extending)

**Comment by twelch** [comment]
template-ocean-eez as part of project `init` now adds a default geography and datasource with bboxFilter and propertyFilter based on the users chosen EEZ at project creation.

If report developer has a new planning boundary, they would just need to import it and create or switch over to the new geography.
