### ISSUE TITLE
add support for nan values in raster with nan nodata value

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#171]
May just be able to pass nan as the nodata value and it will just work, but otherwise sum will not work properly.

**Comment by avmey** [comment]
Geoblaze doesn't support NaN as no-data value. Easiest solution might be to overwrite nodata value on data import. It would also remove an import step for the user + make dist rasters more consistent

**Comment by avmey** [comment]
Looking into this. With new raster import, noData value is read from the raster. Considering geoblaze doesn't support NaN values, current plan is to check if noData value is NaN and, if so, set to -9999. This can be done using the `-dstnodata ${config.noDataValue}` flag in `gdalwarp`
