### ISSUE TITLE
Deploying preprocessing scripts without a client throws a lot of errors

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#18]
It's perfectly valid to have a project with no clients when developing preprocessing scripts, and this in fact might be the first step in the workflow. Calling `npm run bootstrap|build|deploy` succeeds but it also spits out a lot errors. We should detect when a client isn't present and skip those build and deployment steps.

**Comment by twelch** [comment]
Valid scenarios I see to support:
- client with no functions (any functions are client-side and computed at runtime, example  gp-area template)
- functions with no clients, including preprocessor function only (example of initial deploy with just a preprocessor)

**Comment by twelch** [comment]
Questions
* is RUN_AS_SYNC defaulting to false the right answer?  Does the variable mean the opposite of what I think?
