### ISSUE TITLE
test:scripts fails on MacOS

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#180]
On MacOS, `npm run test:scripts` runs for ~15s before jest throws a RangeError. 

```
> @seasketch/geoprocessing@2.0.0 test:scripts
> jest --group=-scripts/e2e --projects scripts

/Users/avmey/geoprocessing/packages/geoprocessing/node_modules/jest-haste-map/build/crawlers/node.js:249
  child.stdout.on('data', data => (stdout += data));
                                             ^

RangeError: Invalid string length
    at Socket.<anonymous> (/Users/avmey/geoprocessing/packages/geoprocessing/node_modules/jest-haste-map/build/crawlers/node.js:249:46)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

- No console statements log in jest.setup.ts
- `npm run test` completes when `npm run test:scripts` is removed from command

**Comment by twelch** [comment]
What happens if you comment out the code in jest.setup.ts?  Does it then start the test runs but lots fail because there's no server serving up files?

**Comment by avmey** [comment]
No, it actually still returns the same error with no sign of the script tests running. So it must fail somewhere other than jest.setup.ts

**Comment by avmey** [comment]
Maybe you're remembering when I ran `npm run test` and the `jest --group=-e2e` part runs and passes 28 test suites, then hangs on the `npm run test:scripts` part. I don't recall the `npm run test:scripts` part ever working (but I could be wrong). I tried removing startup and teardown scripts from config and `npm run test:scripts` still errors.
