### ISSUE TITLE
Test out equal area projection use with geoblaze

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#188]
Testing geoblaze handling of ESRI:54012 Eckert IV equal-area projection

Tests:

- [x] Compare geoblaze statistics of ESRI:54012 COG with QGIS raster statistics output for discrete (0,1) raster
- [x] Compare geoblaze statistics of ESRI:54012 COG with QGIS raster statistics output for continuous (0-1) raster
- [x] Compare geoblaze statistics of ESRI:54012 COG with QGIS raster statistics output when raster crosses the dateline -- Fails
- [x] Compare geoblaze stats of ESRI:54012 COG with QGIS raster output with polygon feature
- [x] Compare geoblaze stats of ESRI:54012 COG with QGIS raster output with overlapping polygons

**Comment by twelch** [comment]
I think Eckert IV is the equal area projection that it was discussed to use.  Suitable for large scale global as well as local analysis without switching between projections (UTM).  Also is meters based.
https://epsg.io/54012

More info:
* https://gis.stackexchange.com/questions/28031/projections-appropriate-for-global-analysis-that-preserve-area-and-that-preserve
