### ISSUE TITLE
Update GP handlers to support additional parameters

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#195]
For use in sub-regional planning. Current thought is to send an open-ended JSON objects as parameter for other potential uses. Caching will have to be updated to include the parameter in the key.

**Comment by twelch** [comment]
Report client can load ResultsCard with extra parameters directly:
`<ResultsCard functionName='boundaryAreaOverlap' extraParams={{foo: 'bar'}} />`

It then passes them to useFunction:
