### ISSUE TITLE
Antimeridian tests

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#199]
Stored in antimeridian branch. Testing handling of antimeridian crossing.

See tests [here](https://github.com/seasketch/geoprocessing/blob/67473c7e3b7e10c60833e1d2bb34bdf598c65445/packages/geoprocessing/src/toolbox/geoblaze/antimeridian.test.ts#L132) and detailed output [here](https://docs.google.com/document/d/11qZQawgfn-BhudGsHTvb-Wqu0Rv6WU6yg8UCIw8Pt0U/edit#heading=h.so8v146nbpz0)

Clip geometries in user space (geojson-antimeridian-cut with cleanCoords).
[splitting](https://github.com/mcclintock-lab/nz-national-reports/blob/master/src/functions/clipToOceanEez.ts#L86), [cleanCoords](https://github.com/mcclintock-lab/nz-national-reports/blob/9e858173ec2c5509809ced69868877c9a7529862/src/functions/clipToOceanEez.ts#L83), and [cleanCoords](https://github.com/mcclintock-lab/nz-national-reports/blob/master/src/util/cleanCoords.ts)

Tests to write
- [x] geojson and raster both cross antimeridian
- [x] raster crosses antimeridian, geojson does not
- [x] check all types of cross-antimeridian coordinates resolve to the same split coordinates

**Comment by twelch** [comment]
Reminder that geoblaze-upgrade branch has been merged.  Feel free to push a new branch with additional tests
