### ISSUE TITLE
New client implementation is slow for sync reports and breaks caching

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#20]
I'm seeing ~3 second pauses in most cases when loading sync reports after the changes to accommodate async reports. The client appears to make multiple fetches immediately for results. Even if the result is in local client cache it results in a long pause, so closing and immediately opening the same report doesn't have the immediate rendering like it used to. It also seems like the first run without a cache hit is slower since the lambda is having to field lots of duplicative requests all at once.

**Comment by underbluewaters** [comment]
On second look I'm not sure caching is broken necessarily. It's hard to pin down the exact source of slowness because *so* much is going on. The first step to optimizing this is going to be to reduce the number of requests.

I've posted a shape to the guyana project who's report consists of a single sync service (http://seasket.ch/iwrRHWgejn). Running this triggers a whopping 15 requests! 3 of those are for the iframe content, metadata doc, and report js bundle. Can't do much more to optimize those. But that still leaves 11 redundant requests. All these put a substantial amount of extra load on the lambda and slow down rendering. At that bursty of a rate it might even force the cold-start of additional lambda instances.

<img width="1737" alt="Screen Shot 2020-08-17 at 7 55 52 AM" src="https://user-images.githubusercontent.com/511063/90410864-c5025200-e05f-11ea-9941-f8fb79bf2d41.png">

**Comment by twelch** [comment]
This might be resolved just be splitting out into its own AsyncGeoprocessingHandler, instead of everything being lumped into the one GeoprocessingHandler for all lambda use cases

**Comment by twelch** [comment]
This appears to be resolved.  Only one request is sent for each sync function, and 2 for each async function.
