### ISSUE TITLE
Totals can be 0 in subregion

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#203]
In single-region reports, all layers had values in the planning region. In multi-region reports, a data layer may be present in the larger region but not present in the subregion (ex. a species is present in the Azores nearshore but not in the Santa Maria nearshore region). This results in the denominator/total being 0, causing the % overlap to be infinity, NaN, or 0 depending on a variety of factors. This is confusing to a user, who may be trying to reach an objective goal for each species, as they would never be able to hit this obejctive due to the species not being present at all.

![Image](https://github.com/seasketch/geoprocessing/assets/22669217/920f2b5e-824c-4c16-b9d3-06a8f5d93074)

The current handling is to overwrite these values as 0 and 0% overlap, and it is up to users to check the associated map layer to understand the 0% overlap. 

The future solution will be to make a part of this process smarter, by removing the row from the ClassTable if total is 0 and adding a note that the data layer is not present in the region.

**Comment by twelch** [comment]
Resolved via #208
