### ISSUE TITLE
GP release missing some baseLang languages

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#210]
Specifically 4.0.1-alpha.2 shows this behavior. Updating azores-nearshore-reports to 4.0.1-alpha.2 causes ~8 baseLang translation.json files to be deleted. GP 4.0.1-alpha.3 does not show this behavior.

**Comment by twelch** [comment]
Yeah there was a bug that was fixed.  I can't remember the specifics.  Is there something to be done here?

**Comment by twelch** [comment]
Feel free to re-open if the issue persists.
