### ISSUE TITLE
Sketch attributes don't translate unless added to baseLang

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#214]
![Image](https://github.com/seasketch/geoprocessing/assets/22669217/0b544cb5-5cde-4285-bf32-8ec208bc8cfe)

Only attributes that are in baseLang are translated in the SketchAttributeCard. Is there a way to collect these values or should attributes be added to baseLang?

**Comment by twelch** [comment]
@avmey You translate the attributes in the seasketch admin

**Comment by twelch** [comment]
@avmey You translate the attributes in the seasketch admin

Assuming you mean new sketch attributes added for a project

**Comment by avmey** [comment]
@twelch Hm, the word "Comments" is translated in sketch admin, but doesn't translate in the reports.

**Comment by twelch** [comment]
@avmey can you post a sample sketch here for testing?  The translations should be embedded.  Is the translation for `Comments` included?

**Comment by avmey** [comment]
Yep, here's the example that I've been using. The translations look to be embedded correctly.
[test.geojson.json.zip](https://github.com/seasketch/geoprocessing/files/12491053/test.geojson.json.zip)

**Comment by twelch** [comment]
Should be resolved via 432b1295d762b82d0c79c537e9896ed452c8337e.  Not yet published.
