### ISSUE TITLE
Caching broken

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#22]
After editing a feature report results aren't update and instead use the same old cached results. I'm testing with an async service right now. Not sure if it effects async services. I'll do some investigating to see if this is only a client issue or is a problem in the lambda system as well.

**Comment by underbluewaters** [comment]
Looks like I was wrong about the root cause of this. SeaSketch is sending the wrong geometry to geoprocessing! At least, after editing the shape. Not sure what that's about. Will have to pick it back up tomorrow.

**Comment by twelch** [comment]
I believe this was fixed recently on the seasketch side here - https://github.com/mcclintock-lab/SeaSketch/commit/19c6f7305ddccdb3ec8c900379420fca603546df
