### ISSUE TITLE
overlapFeatures double counts in sum operation

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#225]
Calling overlapFeatures sum on a sketch collection can return doubly-counted features without an option to enforce single counting. 

For example in Bermuda, three small sketches fall inside of a feature which represents 15 shipwrecks. Each sketch is assigned as containing 15 shipwrecks. The sketch collection triple counts these 15 shipwrecks and reports 45 shipwrecks.

![Image](https://github.com/seasketch/geoprocessing/assets/22669217/07b42bdd-827d-4c43-9146-3adf247e5be3)
(The small shape at the bottom is 3 sketches. NumberofRe is the parameter of number of shipwrecks.)

![Image](https://github.com/seasketch/geoprocessing/assets/22669217/a93e97ff-b68f-49b4-81fb-ae66bc06f4ed)

Solution:  Track unique id of features to ensure each feature can only be counted once in the sum.

**Comment by twelch** [comment]
This is probably a bug. I can't see any reason would want to double count.  For computing metrics for the collection as a whole, overlapFeatures is designed to union the sketch collection to get rid of overlap.  It doesn't seem to be doing that properly.  I also don't see that the unit tests include a test for sum

**Comment by twelch** [comment]
At first glance, it's looping through each of the unioned result, and is simply incrementing the count if there's any intersect.  It probably needs a way to keep track of whether a feature has already been counted.  Maybe using an unique ID property that gets added to the unioned results features first

**Comment by twelch** [comment]
Err, ID that gets added to the shipwreck features I guess I meant

**Comment by avmey** [comment]
Agreed, sounds good. I'll be adding this in project space for Bermuda since it's behind in GP releases, then can make the edit with tests in the framework.

**Comment by twelch** [comment]
yeah that's probably the right approach

**Comment by avmey** [comment]
Jsyk, the union of sketches is working properly, these sketches don't overlap which is why they aren't dissolved together.
<img width="505" alt="Screenshot 2023-09-28 at 10 47 07 AM" src="https://github.com/seasketch/geoprocessing/assets/22669217/cf24a8e6-563c-4912-8ffb-fd7c28d58a05">
