### ISSUE TITLE
overlapRaster and overlapFeatures don't seem to default to truncate = false

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#229]
@avmey in merging your truncate work into my subregional branch, I noticed that in overlapRaster and overlapFeatures the docs imply that `truncate` should default to false.  But I'm not seeing that the truncate option is ever checked, and suspect it is defaulting to true.  Your tests seems to pass true, and might not catch it.

https://github.com/seasketch/geoprocessing/blob/0c8eee71242799b8d720e3b07efac8463ce79a13/packages/geoprocessing/src/toolbox/overlapRaster.ts#L31

**Comment by twelch** [comment]
Do you feel strongly that truncate should default to false? It does make it explicit.  That said, maybe the default should be true so the caller doesn't have to know.  Either way, it seems the option might not be hooked up.

**Comment by avmey** [comment]
Thanks for spotting this, it's definitely not linked in. I think you bring up a good point -- it seems to make more sense to default to true, so a caller doesn't have to think about it and should have a good reason for keeping untruncated values.

**Comment by twelch** [comment]
Yeah default true sounds fine
