### ISSUE TITLE
Add support for report printing/pdf

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#236]
Project partners would like to be able to print hard copies of sketch reports or export digital hard copies of reports (PDF)

In its simplest form this could be:
- A button available in the corner of the report window
- Clicking the button will open up a new browser tab and load a full width report.
 - Relevant header information will be included up top - sketch name, last modified data/time, current date/time.
 - This could be as simple as loading reports in "masonry" layout, 2 wide
 - Learn more dropdowns could just be removed
 - Show by mpa would be displayed in long row form, instead of side scroll form.  It could even be split out into a separate report section so that no one report spans more than a page vertically.
- Printing this browser tab could add some additional print css if needed, like adding the sketch name

Implementation
- a new endpoint could be published with a separate react "PrintApp" just for this purpose

PDF support
- Simplest implementation of this could be to use the Print to PDF feature of all modern browsers/operating systems.

Stretch goal
- a visual representation of the mpa could be displayed using the geojson, coastline and eez. See d3-js.

**Comment by underbluewaters** [comment]
In the past we've used phantomjs to take a screenshot of the browser viewport and export that to pdf. It would be nice if we had a similar pdf service that can be accessed with a link. phantomjs is out of date but SSN is taking map screenshots using puppeteer paired with a lambda layer:

https://github.com/seasketch/next/tree/master/packages/map-screenshotter

**Comment by avmey** [comment]
@twelch Thoughts on anything that needs to be resolved further before closing this issue? (i.e. the stretch goal)

**Comment by twelch** [comment]
@avmey The stretch goal sounds like fun if you want to go for it. Welcome to close as-is as well.

**Comment by avmey** [comment]
It does sound fun, I'll give it a go

**Comment by twelch** [comment]
@avmey deciding where/how to to get your hands on the spatial data might be the most challenging part.

The sketch geojson can be pretty large, so the report react app doesn't currently handle it at all I think, it passes the sketch geometryUri on to the lambdas to fetch it from seasketch directly via the `geometryUri` in GeoprocessingHandler, and the geometry is set to null in the geoprocessing function response.  We don't ship it back with the lambda response because it can quickly be larger than the maximum payload size that can be returned.

So a couple of options off the top of my head:

1 - If you want to generate the image on the client, one option is to have the browser client use the geometryUri and ProjectClient datasource URLs to fetch the data needed asynchronously, when the report is initialized, maybe in App.tsx, and have it stored.ready to use say in the report context.  d3could be invoked in your print widget to render the image.
2 - another option might be to use a web worker in the browser to fetch data and do as much work as possible, then ship the result back to the main browser thread to display the result.  Chad would probably be happy to talk about how this works as he has envisioned being able to run geoprocessing functions in web workers even at some point instead of using lambdas.  This could be a first test case.
3 - create a geoprocessing function that does most all of the work for you, and possibly gets all the way to returning an image (svg or base 64 encoded png), or possibly some very simplified geometries for display if it can keep the payload small enough.

**Comment by twelch** [comment]
d3 web worker example - https://gist.github.com/mbostock/01ab2e85e8727d6529d20391c0fd9a16

**Comment by twelch** [comment]
d3 server-side example with jsdom - https://github.com/gregjopa/d3-server-side-demo/blob/main/bar_chart_helper.js.

https://www.gregjopa.com/2020/05/render-d3-charts-server-side

**Comment by avmey** [comment]
Thanks for all the thoughts and links! I think I'll start with the geoprocessing function to get something worker and go from there.
