### ISSUE TITLE
Not compatible w/node 14

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#25]
Installation process leaves a lot of dependencies out and when these problems are cleaned up it fails to build the client.

**Comment by twelch** [comment]
@underbluewaters do you have a little more detail on this one?  what installation process are you referring to?  Do you mean creating a new report from template?  Thanks.

**Comment by twelch** [comment]
AWS Lambda doesn't appear to support node v15, only 14 as LTS.  I will target the latest 14 (14.16.1 atm) and see if similar issues occur on deploy of fresh project with `gp-area` template installed
