### ISSUE TITLE
allow user to specify raster cell size to use on import

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#260]
Need: a lot of times we are given rasters with cell resolution that is too large or too small for accurate planning.  There's a sweet spot that gives you good accuracy when overlapping with a sketch, but not too detailed.

Once we've switched to using an equal area projection that is in meters, we ccould let the user specify what the resolution should be after import (e.g. `500` meters).  And gdal will resample to that size using the `-tr` option.

https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-tr

Consider adding this via an open-ended `gdalWarpParams` string property for each datasource that gets inserted into the gdalWarp command onimport, so that any number of custom options can be added.  Could even support an open ended Record of which gdalWarpParams is just one possibility.

**Comment by avmey** [comment]
We may run into trouble with `sum` calculations here. While increasing resolution will make our `area` calculations more accurate, I'm not sure there's an easy way to warn against doing any `sum` calculations on imported rasters that have the cell size adjusted.

**Comment by twelch** [comment]
@avmey  You're right the cell values would need to be adjusted, I think it's what's called disaggregation.  Most likely scenario is user would either want to:
* split each large cell value equally amongst the smaller cells, say if the value was total abundance, so that the total sum stays the sum
* keep the parent cell value, for example if the cell represented water depth.

This is ringing some bells for me and reminds me that Daniel is working on a "virtual resampling" feature for Geoblaze that could potentially avoid needing to adjust resolution up front - https://github.com/GeoTIFF/geoblaze/pull/228/files.  And comment in ticket - https://github.com/seasketch/geoprocessing/issues/156#issuecomment-1468029281

I'm not sure if GDAL can do that easily within a single command or even multiple.
- I see this utility - https://github.com/GEMScienceTools/spatial-disaggregation
- discussion of doing it with R - https://stackoverflow.com/questions/73295157/disaggregate-raster-value-to-finer-cells-equally

**Comment by twelch** [comment]
Closed in favor of #284
