### ISSUE TITLE
Version 7.0

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#285]
Other
- [x] #272
- [x] Remove translation:extract from prepare
- [x] Fix clear-all-results command
- [x] make script names consistent (e.g. install:scripts, translation:install)
- [x] Remove any project-space files that can be removed (babel? if translation:extract goes internal)
- [x] Remove leftover jest references, and use of `group` directives`
- [x] Update clipToGeography with latest enhancements in california-reports
- [x] Add prettier (include project config json files).
- [x] Add eslint.  Fix all error.  Then add lint-staged.
- [x] baseLangResourcez debug logging
- [x] Deprecate clip function, for turf
- [x] start-data to start:data
- [x] Remove loadCogWindow and loadCog
- [x] Remove any other past deprecated
- [x] Change toSketchProperties array to toChildProperties, 
- [x] make sure genSketch creates within eez, loop and check until true
- [x] raster import is just geotiff, don't ask what formats the user wants.
- [x] Simplify fsm example data, precalc taking forever
- [x] Remove template-ocean-eez?
- [x] simplify reef extent and benthic dataset in project
- [x] rename genRandomFeature to genRandomPolygon
- [x] Fix SimpleCard squiggle error with area
- [x] add unit tests to preprocessor function and mock calls to cloudfront vectordatasource
- [x] make sure on upgrade that clipToGeography is updated.
- [x] Create a new page for CoralReefCard and BenthicHabitatCard in sampleProject?
- [x] don't require geojson file for geography import on precalc
- [x] Ask abby do we really need ${datasourceId}_all check is in vectorFunction?  Is there another way to get what you want here?  Is it a feature or a one-off?  Something to be added by example if the user needs it?
- [x] refactor precalc to use loadFgbFromDisk function
- [x] migrate fs.rmDirSync to fs.rm
- [x] #386
- [x] refactor overlapFeatures
- [x] add tests to removeOverlap and toMultipolygon
- [x] unpin aws-cdk version, allow it to upgrade
- [x] bump to node22 in cdk

Abby
- [x] #385
  - error polygon1 ValidationError: Feature is outside of boundary
    at Module.clipToPolygonFeatures (file:///workspaces/test-three/node_modules/@seasketch/geoprocessing/src/toolbox/genPreprocessor.ts:155:11)
    at clipToOceanEez (/workspaces/test-three/src/functions/clipToOceanEez.ts:52:10)
- [x] Fix clear results by report
- [x] filter list in question - Select additional feature properties to keep in final datasource - using answer to last question
- [x] Test migrate California

Other Dependencies
- [x] Upgrade deps, minimize npm install warnings
  - [x] Drop deprecated `request` dependency for fetch with form data
- [x] Add peer? dependencies so that projects know what versions to upgrade to?
- [x] Allow user to select which languages to support in project and filter the list in supported.ts.
- [x] Better support (bring in helper functions).

Bugs

- [x] project package.json `version` is getting set to the version of gp on install.  It should be left as I think 0.1
- [x] lint-staged getting removed from project package.json on upgrade

Improve upgrade
- [x] Consolidate config into project dir - src/i18n/config.json, geoprocessing.json
- [x] Write upgrade script - include first install of scripts, then translation, merge extraTerms, merge package.json dependencies/scripts ,vscode dir, etc.
- [x] If already have dependency, remove from devDependency

AWS
- [x] Upgrade to aws-cdk v3
- [x] Refactor cdk stack testing away from Jest -- https://docs.aws.amazon.com/cdk/v2/guide/testing.html

i18n
- [x] Verify extractExtraTerms script is working properly
- [x] Update core translations.  Make full POEditor cycle is working
- [x] Upgrade react-i18n major upgrade
- [x]  translation:install should check if top-level i18n files all exist including config.json (user may have wiped it out) and copy over if not.
- [x] publish latest translations and rerun for languages

React
- [x] React version 18

Test Tooling
- [x] https://github.com/seasketch/geoprocessing/issues/254

Document
- [x] Document minimum migration steps for any given release - run all install scripts, update dependency versions to at least what is in base-project and whatever template you used.
- [x] How to run tests, no more smoke or unit specific for projects
- [x] use of npm-check-updates -- `ncu --interactive --format group`
- [x] how to do a prerelease.  after first one have to select "custom prerelease" to advance it.
- [x] Review and update migration steps, including package.json list
- [x] Document run of `translation:extract` in tutorial now that is not run automatically on each `npm install`
- [x] Add link to release on front page.
- [x] Document how to run individual smoke tests, how to debug in vscode
- [x] How to use lambda worker helper function
- [x] clear:result and start:data
- [x] Clarify that user can add new language code manually
- [x] upgrade clarify that will overwrite files and directories
- [x] Drop the notion of codespaces
- [x] Rollback docs for 6.1.0 - report templates, and updates to importing datasources, fetching layers and attributes to select from as opposed to typing them out
- [x] Fix sketchAttributes.md links
- [x] Remove toNullSketch from defaults
- [x] Add create:report doc and any other, next to CLI page.
- [x] move all the ways of linking data to a sub-page.  Tutorial can just use FSM example data.
- [x] Import raster is asking vector questions in 6.1.2, make sure not in 7.0
- [x] Pull the extra metric group examples (fishRichness etc.) out to a metric group guide in 7.0
- [x] Recommend devcontainer for Mac, WSL Ubuntu for Windows, 
  - How to copy files to devcontainer on Windows?
  - What does Abby do on a mac
- [x] add polygonSmokeTest function
- [x] update antimeridian page to account for new functions and fixes
- [x] Add wsl distribution publish steps to Contributing
- [x] Make sure data linking is up to date, including how to mount Box drive in macOS
- [x] document "the right way" to do a simple intersect using geoprocessing.  Look at genPreprocessor, it has best way to do an intersect and a difference.
- [x] Update [metric group](https://seasketch.github.io/geoprocessing/docs/next/concepts/AdvancedConcepts/#metric-group) examples
- [x] Drop geography code from simple reports, leave in createReport.
- [x] Document setting of environment before aws deploy
- [x] drop mention of macos support
- [x] disable the old wiki
- [x] link toolbox page commands to their api docs
- [x] Update version 7 migration steps, pulling from previous betas.
- [x] how to copy to/from datasets bucket directly
- [x] Write toolbox unit tests.  make sure that union is like a dissolve

Tutorial
- [x] Make sure registering of stories is consistent across examples.  Why was a top-level CoralReef report client created?

Release Testing

- Init new project
- Verify translation is setup and works properly, remoteContext is set to project name
- [x] Test all preprocessors
- [x] Deploy and test full report migration in SeaSketch
- [x] Delete all test stacks deployed
- [x] gp-workspace Windows release

Follow-on tickets:
-  #395
- datasource filters and such and getDatasourceFeatures
- document, my geoprocessing function is too slow, what do I do?
  - Subdivide your data, use getFeaturesForSketchBBox, look into functions like clipMultiMerge, increase Lambda memory up to 10GB, use workers, simplify your data.
- publish both a sync and async version of simpleFunction calculating area of the sketch on a fresh stack and see how they compare first run and thereafter both cached and uncached
- Verify sample tutorial results in QGIS
- If import extension is fgb or shp then don't need to ask for layer name, just use basename of file
- add more tests to getFeaturesForSketchBboxes, tests to the split bbox functions
- migrate getFeatures.test.ts to be e2e and use locally served fgb like flatgeobuf.test.e2e.ts
- `deploy` command is using npx, which runs the latest cdk instead of what geoprocessing has installed.  how to specify local?
- prettier is not working by default, what's up. extensions are they asked to be installed recommended?
- rasterStats could get a `solveOverlap` option that assumes sketches don't overlap and sums the 
- add overlapPoints (montserrate reports)
- The datasource format name of "subdivided" is a mistake. any format can have subdivided polygons, that's not what makes VectorDataSource unique.
- website doc location in folders don't quite align with where pages are in the sidebar hierarchy.  Some of the names aren't clear like top-level page in Tutorials.md but it's more specific than that.

**Comment by avmey** [comment]
@twelch Looking into your bullet `filter list in question - Select additional feature properties to keep in final datasource - using answer to last question`. You may have already addressed it, unless I'm misunderstanding the suggestion. It seems like the list already filters out variables that were selected in the previous question

**Comment by twelch** [comment]
Closed via 74b41c20c652cbf1d3107a3fe6c6ac1f27018bf1
