### ISSUE TITLE
Unexpected area results from polygons with holes

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#310]
QGIS and geoprocessing return very different areas for the intersection between `rocky_shores` and `mpa_test`

[Archive.zip](https://github.com/user-attachments/files/16058220/Archive.zip)

**Comment by twelch** [comment]
Resolved by regenerating package-lock.json and node_modules directory in the geoprocessing project it was occurring.  Can only guess there was some issue with a dependency or an older version the lockfile was retaining.
