### ISSUE TITLE
Spaces in example sketch names break storybook

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#372]
I dragged & dropped a sketch from my project into the `examples/sketches` directory and it appears any spaces or special characters will break the storybook output.

![Screenshot 2024-11-19 at 8 33 41 AM](https://github.com/user-attachments/assets/5a775366-9788-4073-a1d6-ed6cf85c29ba)

**Comment by twelch** [comment]
Resolved in 7.0.0-experimental-7x-docs.82 release
