### ISSUE TITLE
Support async executionModel

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#4]
For geoprocessing functions that take longer that a second or two, authors should choose `async` as the executionModel. GeoprocessingHandler will need to be modified to call functions in a separate lambda handler and inform clients via API Gateway's websocket support. `useFunction` will also need to be modified to act as a client for these services.

**Comment by underbluewaters** [comment]
Rough implementation steps
  - [ ] Modify createStack to create an api gateway websocket endpoint to be used by handlers
  - [ ] Update tasks.ts, GeoprocessingHandler.ts, and any other files needed to pass accurate WSS:// info to the response when running an async task
  - [ ] Create AsyncGeoprocessingHandler class which works much like GeoprocessingHandler but notifies the api gateway websocket of any updates to the task (pass or failure).
  - [ ] Modify webpack.functions.config.js to produce final async handlers and include them in compiled output in `.build`. Async handlers should only be built if the report implementation is in fact async.
  - [ ] Modify createManifests.ts to add async handlers to the output
  - [ ] Update createStack to look for async handlers and deploy them as lambdas, passing any websocket configuration needed via environment variables
  - [ ] Verify process works using chrome dev tools
  - [ ] Update useFunction to appropriately handle websocket-based responses
  - [ ] **Important** Create unit tests for useFunction and AsyncGeoprocessingHandler to ensure proper functioning, even in exceptional circumstances (exceptions in geoprocessing function, exceptions in handler code, timeouts(how are they detected?))

**Comment by twelch** [comment]
Docs will need an update with current architecture.

Shortcomings:
* Seems to create one web socket connection per function/results card
* API Gateway, can't have multiple web socket endpoints.  One for the entire stack, which serves all the web socket lambdas.  You will get messages for all functions and have to.

Remaining security concerns:
* All report task messages with IDs are being broadcast to all listeners.  With the REST API these IDs function as a type of non-guessable key.  But with socket there's potential to listen to channel and get other users results.  One possible solution - add signed token associated with user for fetching results.  For sensitive reports don't use/deploy socket access and use long polling (configuration-driven).
* Overall authentication - see https://github.com/seasketch/geoprocessing/blob/master/docs/design/SERVICES_API.md#access-control-tokens

**Comment by underbluewaters** [comment]
See also:
https://github.com/seasketch/geoprocessing/issues/20
