### ISSUE TITLE
Reuse iframes when running report clients

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#9]
The legacy SeaSketch application loads report clients in iframes and discards them once the report window is closed. This prevents caching of some assets and results, increasing latency. If possible iframes should be hidden and reused.

**Comment by twelch** [comment]
This seems like a ticket that should be in SeaSketch next as the manager of the iframe.  Thoughts @underbluewaters?

**Comment by underbluewaters** [comment]
That's right. I'm going to close this ticket since I don't think it's worth trying to optimize legacy SeaSketch further.
